//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class JurnalUmum {
    
    /// <summary>
    /// sm1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager sm1;
    
    /// <summary>
    /// ASPxTabControl1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::DevExpress.Web.ASPxTabControl.ASPxPageControl ASPxTabControl1;
    
    /// <summary>
    /// DaftarJurnalUmum control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Pertamina.PKBL.WebApp.Akuntansi.Jurnal_Umum_Control.DaftarJurnalUmum DaftarJurnalUmum;
    
    /// <summary>
    /// PostingJournal control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Pertamina.PKBL.WebApp.Akuntansi.Jurnal_Umum_Control.PostingJournal PostingJournal;
}
