<%@ Page Title="" Language="C#" MasterPageFile="~/Layout.Master" AutoEventWireup="true" CodeBehind="PenyaluranBLDetail.aspx.cs" Inherits="Pertamina.PKBL.WebApp.Akuntansi.PenyaluranBLDetail" %>

<%@ Register Assembly="DevExpress.Web.v13.2, Version=13.2.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web.ASPxPanel" TagPrefix="dx" %>

<%@ Register Assembly="DevExpress.Web.v13.2, Version=13.2.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web.ASPxPopupControl" TagPrefix="dx" %>

<%@ Register Assembly="DevExpress.Web.v13.2, Version=13.2.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web.ASPxGridView" TagPrefix="dx" %>
<%@ Register assembly="DevExpress.Web.v13.2, Version=13.2.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.Web.ASPxEditors" tagprefix="dx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="html_header" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="BodyContent" runat="server">

    <script type="text/javascript">    
        function Change(s, e) {
            
            if (e.buttonID == 'btnPrint') {
                gvPenyaluran.GetRowValues(e.visibleIndex, 'NoRef', fc);
            }
            else
            {
                debugger;
                e.processOnServer = true;
            }
        }

        function fc(values) {
            window.open('../Reporting/PrintPage.aspx?noref='+values);
        }

    </script>

    <dx:ASPxGridView ID="gvPenyaluranSaldo" ClientInstanceName="gvPenyaluranSaldo" runat="server" OnCustomButtonCallback="gvPenyaluranSaldo_CustomButtonCallback" AutoGenerateColumns="False" EnableTheming="True" Theme="Youthful" Width="100%" >
        <Columns>
            <dx:GridViewDataTextColumn Caption="No Akun" Name="COA" FieldName="COA" VisibleIndex="0" Width="30%">
            </dx:GridViewDataTextColumn>
            <dx:GridViewDataTextColumn Caption="Deskripsi" Name="account_name" FieldName="account_name" VisibleIndex="1" Width="40%">
            </dx:GridViewDataTextColumn>
            <dx:GridViewDataTextColumn Caption="Saldo" Name="SaldoAkhir" FieldName="SaldoAkhir" VisibleIndex="2" Width="30%">
                <PropertiesTextEdit DisplayFormatString="##,#.00"></PropertiesTextEdit>
            </dx:GridViewDataTextColumn>

        </Columns>

        <SettingsPager AlwaysShowPager="false" PageSize="100">
         </SettingsPager>
    </dx:ASPxGridView>

    <div class="bodydetail">
        <div class=" borderdetail">
            <table style="width:60%">
                <tr>
                    <td  style="width:20%">
                        <dx:ASPxLabel ID="lblNoRef" runat="server" Text="No. Ref" Theme="Youthful"></dx:ASPxLabel>
                    </td>
                    <td>
                        <dx:ASPxTextBox ID="txtNoRef" runat="server" Width="83%" Theme="Youthful" NullText="[Auto Generated By System]" ReadOnly="true"></dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblTglPenyaluran" runat="server" Text="Tanggal Penyaluran" Theme="Youthful"></dx:ASPxLabel>
                        <span style="color:red">*</span>
                    </td>
                    <td>
                        <dx:ASPxDateEdit ID="dateTglPenyaluran"  runat="server" DisplayFormatString="dd/MM/yyyy" Theme="Youthful"></dx:ASPxDateEdit>
                    </td>
                </tr>
            </table>
        </div>
        <br/>
        <div class="borderdetail">
            <table style="width:60%">
                <tr>
                    <td  style="width:20%">
                        <dx:ASPxLabel ID="lblUsulanBantuan" runat="server" Text="Usulan Bantuan" Theme="Youthful"></dx:ASPxLabel>
                    </td>
                    <td>
                        <dx:ASPxTextBox ID="txtUsulanBantuan" runat="server" Width="83%" Theme="Youthful"></dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblNoPemohon" runat="server" Text="No. Pemohon" Theme="Youthful"></dx:ASPxLabel>
                        <span style="color:red">*</span>
                    </td>
                    <td>
                        <dx:ASPxTextBox ID="txtNoPemohon" runat="server" Width="83%" Theme="Youthful" ReadOnly="true"></dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblNamaPemohon" runat="server" Text="Nama Pemohon" Theme="Youthful"></dx:ASPxLabel>
                    </td>
                    <td>
                        <dx:ASPxTextBox ID="txtNamaPemohon" runat="server" Width="83%" Theme="Youthful"></dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblKepada" runat="server" Text="Kepada" Theme="Youthful"></dx:ASPxLabel>
                        <span style="color:red">*</span>
                    </td>
                    <td>
                        <dx:ASPxTextBox ID="txtKepada" runat="server" Width="83%" Theme="Youthful"></dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblPermintaanBayar" runat="server" Text="Permintaan Bayar" Theme="Youthful"></dx:ASPxLabel>
                    </td>
                    <td>
                        <dx:ASPxTextBox ID="txtPermintaanBayar" runat="server" Width="83%" Theme="Youthful"></dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblVerifikasi" runat="server" Text="Verifikasi" Theme="Youthful"></dx:ASPxLabel>
                    </td>
                    <td>
                        <dx:ASPxTextBox ID="txtVerifikasi" runat="server" Width="83%" Theme="Youthful"></dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblPenyetuju" runat="server" Text="Penyetuju" Theme="Youthful"></dx:ASPxLabel>
                    </td>
                    <td>
                         <dx:ASPxTextBox ID="txtPenyetuju" runat="server" Width="83%" Theme="Youthful"></dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblDeskripsiBantuan" runat="server" Text="Deskripsi Bantuan" Theme="Youthful"></dx:ASPxLabel>
                        <span style="color:red">*</span>
                    </td>
                    <td>
                         <dx:ASPxTextBox ID="txtDeskripsiBantuan" runat="server" Width="83%" Theme="Youthful"></dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblNilaiPenyaluran" runat="server" Text="Nilai Penyaluran" Theme="Youthful"></dx:ASPxLabel>
                        <span style="color:red">*</span>
                    </td>
                    <td>
                        <dx:ASPxTextBox ID="txtNilaiPenyaluran" runat="server" Width="100%" Theme="Youthful">
                            <MaskSettings Mask="&lt;0..999999999999999g&gt;" IncludeLiterals="DecimalSymbol" ShowHints="false" />
                        </dx:ASPxTextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblNamaAkun" runat="server" Text="Nama Akun" Theme="Youthful"></dx:ASPxLabel>
                        <span style="color:red">*</span>
                    </td>
                    <td>
                        <dx:ASPxComboBox ID="cbbNamaAkun" runat="server" ValueType="System.String" Width="83%" Theme="Youthful"></dx:ASPxComboBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxLabel ID="lblLawanAkun" runat="server" Text="Lawan Akun" Theme="Youthful"></dx:ASPxLabel>
                        <span style="color:red">*</span>
                    </td>
                    <td>
                        <dx:ASPxComboBox ID="cbbLawanAkun" runat="server" ValueType="System.String" Width="83%" Theme="Youthful"></dx:ASPxComboBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxCheckBox ID="checkAkanDiJurnal" runat="server" CheckState="Unchecked" Text="Akan di Jurnal" EnableTheming="True" Theme="Youthful"></dx:ASPxCheckBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <dx:ASPxCheckBox ID="checkKoreksi" runat="server" Text="Koreksi" Theme="Youthful"></dx:ASPxCheckBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span style="color:red">*) Wajib diisi</span>
                    </td>
                </tr>
            </table>
            <br />
            <dx:ASPxButton ID="btnPopup" runat="server" Text="Simpan" AutoPostBack="false" UseSubmitBehavior="false">
                    <ClientSideEvents Click="function(s, e) { pcLogin.Show(); }" />
            </dx:ASPxButton>
            <dx:ASPxHyperLink ID="hlBatal" runat="server" Text="Batal" NavigateUrl="~/Akuntansi/PenyaluranBL.aspx" ></dx:ASPxHyperLink>
                
            <dx:ASPxPopupControl ID="pcLogin" runat="server" CloseOnEscape="true" Modal="True"
                PopupHorizontalAlign="WindowCenter" PopupVerticalAlign="WindowCenter" ClientInstanceName="pcLogin"
                HeaderText="WARNING !" HeaderStyle-HorizontalAlign="Center" AllowDragging="True" PopupAnimationType="Slide" EnableViewState="False" Theme="Youthful">
                <ContentCollection>
                    <dx:PopupControlContentControl runat="server">
                        <dx:ASPxPanel ID="ASPxPanel1" runat="server" Width="310px">
                            <PanelCollection>
                                <dx:PanelContent runat="server">
                                    <table>
                                        <tr>
                                            <td colspan="2">
                                                <dx:ASPxLabel ID="ASPxLabel1" runat="server" Text="Apakah Anda Ingin Menambahkan Nilai Penyaluran Ini ?"></dx:ASPxLabel>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="height:20px"></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align:center">
                                                 <dx:ASPxButton ID="btnSubmit" runat="server" Text="Simpan" OnClick="btnSubmit_Click" UseSubmitBehavior="false" AutoPostBack="false" Theme="Youthful">
                                                     <ClientSideEvents Click="function(s, e) { pcLogin.Hide(); }" />
                                                 </dx:ASPxButton>
                                            </td>
                                            <td style="text-align:center">
                                                <dx:ASPxButton ID="ASPxButton1" runat="server" Text="Batal" Theme="Youthful" AutoPostBack="false" HorizontalAlign="Center" UseSubmitBehavior="false">
                                                    <ClientSideEvents Click="function(s, e) { pcLogin.Hide(); }" />
                                                </dx:ASPxButton>
                                            </td>
                                        </tr>
                                    </table>
                                </dx:PanelContent>
                            </PanelCollection>
                        </dx:ASPxPanel>
                    </dx:PopupControlContentControl>
                </ContentCollection>
            </dx:ASPxPopupControl>
            <br />
            <dx:ASPxLabel ID="lblInfo" runat="server" Text=""></dx:ASPxLabel>
        </div>
    </div>

    <dx:ASPxGridView ID="gvPenyaluran" ClientIDMode="Static" ClientInstanceName="gvPenyaluran" runat="server" OnCustomButtonCallback="gvPenyaluran_CustomButtonCallback" ClientSideEvents-CustomButtonClick="Change" AutoGenerateColumns="False" Width="100%" Theme="Youthful" OnHtmlRowPrepared="gvPenyaluran_HtmlRowPrepared">
        <Columns>
            <dx:GridViewDataTextColumn Caption="No." VisibleIndex="0">
            </dx:GridViewDataTextColumn>
            <dx:GridViewDataTextColumn Caption="No. Ref" Name="NoRef" FieldName="NoRef" VisibleIndex="1">
            </dx:GridViewDataTextColumn>
            <dx:GridViewDataDateColumn Caption="Tgl. Penyaluran" Name="TglPenyaluran" FieldName="TglPenyaluran" VisibleIndex="2">
                <PropertiesDateEdit DisplayFormatString="dd/MM/yyyy"></PropertiesDateEdit>
            </dx:GridViewDataDateColumn>
            <dx:GridViewDataTextColumn Caption="JBL" Name="JenisBL" FieldName="JenisBL" VisibleIndex="3">
            </dx:GridViewDataTextColumn>
            <dx:GridViewDataTextColumn Caption="Nilai Penyaluran" Name="NilaiPenyaluran" FieldName="NilaiPenyaluran" VisibleIndex="4">
                <PropertiesTextEdit DisplayFormatString="##,#.00"></PropertiesTextEdit>
            </dx:GridViewDataTextColumn>
            <dx:GridViewDataTextColumn Caption="Deskripsi Bantuan" Name="DeskripsiBantuan" FieldName="DeskripsiBantuan" VisibleIndex="5">
            </dx:GridViewDataTextColumn>
            <dx:GridViewCommandColumn Caption="Opr." VisibleIndex="6" ButtonType="Image">
                <CustomButtons>
                    <dx:GridViewCommandColumnCustomButton ID="btnPrint" Image-Url="~/content/images/print.png"></dx:GridViewCommandColumnCustomButton>
                </CustomButtons>
                <CustomButtons>
                    <dx:GridViewCommandColumnCustomButton ID="btnEdit" Image-Url="~/content/images/edit.png"></dx:GridViewCommandColumnCustomButton>
                </CustomButtons>
            </dx:GridViewCommandColumn>
        </Columns>
        <Settings ShowFooter="true" />

        <TotalSummary>
            <dx:ASPxSummaryItem SummaryType="Sum" FieldName="NilaiPenyaluran" ShowInColumn="NilaiPenyaluran" DisplayFormat="Total : {0:##,#}.00" />
         </TotalSummary>
        <Styles>
            <CommandColumn Spacing="5px" />
            <EditingErrorRow HorizontalAlign="Right">
            </EditingErrorRow>
            <FocusedRow BackColor="#ffffff" ForeColor="#000000"></FocusedRow>
        </Styles>
        <StylesPager>
             <CurrentPageNumber BackColor="#FB000C" >
             </CurrentPageNumber>
        </StylesPager>
    </dx:ASPxGridView>
    <br />
    <dx:ASPxLabel ID="lblSisa" runat="server" Text="Sisa Penyaluran : " Theme="Youthful" Font-Bold="true"></dx:ASPxLabel>
    <dx:ASPxLabel ID="lblsisaPEnyaluran" runat="server" Text="" Theme="Youthful" Font-Bold="true" ></dx:ASPxLabel>

    <asp:HiddenField ID="hfId" runat="server" />
    <asp:HiddenField ID="hfNama" runat="server" />
    <asp:HiddenField ID="hfNo" runat="server" />
    <asp:HiddenField ID="hfNil" runat="server" />

</asp:Content>



<asp:Content ID="Content4" ContentPlaceHolderID="FooterContent" runat="server">
</asp:Content>
