//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pertamina.PKBL.WebApp.Kemitraan.ListKemitraan {
    
    
    public partial class ListKemitraanAll {
        
        /// <summary>
        /// ASPxLabel16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxEditors.ASPxLabel ASPxLabel16;
        
        /// <summary>
        /// ListKemitraanJKR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Pertamina.PKBL.WebApp.Kemitraan.ListKemitraan.ListKemitraanJKR ListKemitraanJKR;
        
        /// <summary>
        /// ListKemitraanJDB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Pertamina.PKBL.WebApp.Kemitraan.ListKemitraan.ListKemitraanJDB ListKemitraanJDB;
        
        /// <summary>
        /// ListKemitraanJSU control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Pertamina.PKBL.WebApp.Kemitraan.ListKemitraan.ListKemitraanJSU ListKemitraanJSU;
    }
}
